const express=require('express');const cors=require('cors');const jwt=require('jsonwebtoken');const mongoose=require('mongoose');const crypto=require('crypto');
const app=express();app.use(cors({origin:true}));app.use(express.json());
const PORT=process.env.PORT||3000, JWT_SECRET=process.env.JWT_SECRET||'CHANGE_THIS_JWT_SECRET', MONGO_URL=process.env.MONGO_URL;if(!MONGO_URL){console.error('ERROR: MONGO_URL is not set.');process.exit(1)}
function verifyPassword(p,s){try{const [salt,stored]=String(s||'').split(':');const h=crypto.scryptSync(p,salt,64).toString('hex');const a=Buffer.from(h,'hex'),b=Buffer.from(stored,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
const userSchema=new mongoose.Schema({username:String,passwordHash:String,role:String,balance:{type:Number,default:0},currency:{type:String,default:'USDT'},totalProfit:{type:Number,default:0},referralCode:String,referredBy:String,createdAt:{type:Date,default:Date.now}},{collection:'users'});
const productSchema=new mongoose.Schema({name:String,category:String,price:Number,profitRate:Number,active:{type:Boolean,default:true}},{collection:'products'});
const txSchema=new mongoose.Schema({userId:mongoose.Schema.Types.ObjectId,type:String,amount:Number,status:String,note:String,createdAt:{type:Date,default:Date.now}},{collection:'transactions'});
const msgSchema=new mongoose.Schema({userId:mongoose.Schema.Types.ObjectId,sender:String,text:String,read:{type:Boolean,default:false},createdAt:{type:Date,default:Date.now}},{collection:'messages'});
const auditSchema=new mongoose.Schema({adminId:mongoose.Schema.Types.ObjectId,action:String,targetUserId:mongoose.Schema.Types.ObjectId,targetTransactionId:mongoose.Schema.Types.ObjectId,details:String,createdAt:{type:Date,default:Date.now}},{collection:'admin_audits'});
const User=mongoose.model('AdminUser',userSchema),Product=mongoose.model('AdminProduct',productSchema),Transaction=mongoose.model('AdminTransaction',txSchema),Message=mongoose.model('AdminMessage',msgSchema),Audit=mongoose.model('AdminAudit',auditSchema);
function tokenFor(a){return jwt.sign({id:a._id.toString(),username:a.username,role:a.role},JWT_SECRET,{expiresIn:'12h'})}
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({success:false,message:'Admin login required'});try{req.admin=jwt.verify(h.slice(7),JWT_SECRET);if(req.admin.role!=='admin')throw 0;next()}catch{return res.status(401).json({success:false,message:'Invalid or expired admin token'})}}
async function audit(a,action,details,extra={}){await Audit.create({adminId:a.id,action,details,targetUserId:extra.targetUserId,targetTransactionId:extra.targetTransactionId})}
app.get('/',(q,r)=>r.json({success:true,service:'Zonguru Admin Server',status:'online'}));
app.post('/api/admin/login',async(q,r)=>{try{const username=String(q.body.username||'').trim().toLowerCase(),password=String(q.body.password||'');const a=await User.findOne({username,role:'admin'});if(!a||!verifyPassword(password,a.passwordHash))return r.status(401).json({success:false,message:'Invalid admin username or password'});r.json({success:true,token:tokenFor(a),admin:{id:a._id,username:a.username,role:a.role}})}catch{r.status(500).json({success:false,message:'Admin login failed'})}});
app.get('/api/admin/users',auth,async(q,r)=>r.json({success:true,users:await User.find({role:'user'}).select('-passwordHash').sort({createdAt:-1})}));
app.post('/api/admin/users/:id/balance-adjust',auth,async(q,r)=>{const d=Number(q.body.delta);if(!Number.isFinite(d)||d===0)return r.status(400).json({success:false,message:'Invalid balance adjustment'});const u=await User.findOne({_id:q.params.id,role:'user'});if(!u)return r.status(404).json({success:false,message:'User not found'});const next=Number((Number(u.balance||0)+d).toFixed(2));if(next<0)return r.status(400).json({success:false,message:'Balance cannot be negative'});u.balance=next;await u.save();await audit(q.admin,d>0?'BALANCE_ADD':'BALANCE_SUBTRACT',`${d>0?'+':''}${d.toFixed(2)} ${u.currency}; new balance ${next.toFixed(2)}`,{targetUserId:u._id});r.json({success:true,user:{id:u._id,username:u.username,balance:u.balance,currency:u.currency}})});
app.get('/api/admin/transactions',auth,async(q,r)=>r.json({success:true,transactions:await Transaction.find().sort({createdAt:-1}).limit(500)}));
app.post('/api/admin/transactions/:id/approve',auth,async(q,r)=>{const t=await Transaction.findById(q.params.id);if(!t||t.status!=='pending')return r.status(400).json({success:false,message:'Transaction is not pending'});const u=await User.findById(t.userId);if(!u)return r.status(404).json({success:false,message:'User not found'});if(t.type==='deposit')u.balance=Number((u.balance+t.amount).toFixed(2));else if(t.type==='withdraw'){if(u.balance<t.amount)return r.status(400).json({success:false,message:'User balance is insufficient'});u.balance=Number((u.balance-t.amount).toFixed(2))}t.status='approved';await u.save();await t.save();await Message.create({userId:u._id,sender:'admin',text:`${t.type==='deposit'?'Deposit':'Withdrawal'} request was approved.`});await audit(q.admin,'TRANSACTION_APPROVE',`${t.type} ${t.amount}`,{targetUserId:u._id,targetTransactionId:t._id});r.json({success:true,message:'Transaction approved'})});
app.post('/api/admin/transactions/:id/reject',auth,async(q,r)=>{const t=await Transaction.findById(q.params.id);if(!t||t.status!=='pending')return r.status(400).json({success:false,message:'Transaction is not pending'});t.status='rejected';const note=String(q.body.note||'').trim();if(note)t.note=`${t.note||''} | ${note}`;await t.save();await Message.create({userId:t.userId,sender:'admin',text:`${t.type==='deposit'?'Deposit':'Withdrawal'} request was rejected.`});await audit(q.admin,'TRANSACTION_REJECT',`${t.type} ${t.amount}${note?' - '+note:''}`,{targetUserId:t.userId,targetTransactionId:t._id});r.json({success:true,message:'Transaction rejected'})});
app.get('/api/admin/products',auth,async(q,r)=>r.json({success:true,products:await Product.find().sort({price:1})}));
app.post('/api/admin/products',auth,async(q,r)=>{const name=String(q.body.name||'').trim(),category=String(q.body.category||'General').trim(),price=Number(q.body.price),profitRate=Number(q.body.profitRate);if(!name||!Number.isFinite(price)||price<=0||!Number.isFinite(profitRate)||profitRate<0)return r.status(400).json({success:false,message:'Invalid product data'});const p=await Product.create({name,category,price,profitRate,active:true});await audit(q.admin,'PRODUCT_CREATE',name);r.status(201).json({success:true,product:p})});
app.patch('/api/admin/products/:id',auth,async(q,r)=>{const a={};if(q.body.name!==undefined)a.name=String(q.body.name).trim();if(q.body.category!==undefined)a.category=String(q.body.category).trim();if(q.body.price!==undefined)a.price=Number(q.body.price);if(q.body.profitRate!==undefined)a.profitRate=Number(q.body.profitRate);if(q.body.active!==undefined)a.active=Boolean(q.body.active);const p=await Product.findByIdAndUpdate(q.params.id,a,{new:true});if(!p)return r.status(404).json({success:false,message:'Product not found'});await audit(q.admin,'PRODUCT_UPDATE',p.name);r.json({success:true,product:p})});
app.delete('/api/admin/products/:id',auth,async(q,r)=>{const p=await Product.findByIdAndDelete(q.params.id);if(!p)return r.status(404).json({success:false,message:'Product not found'});await audit(q.admin,'PRODUCT_DELETE',p.name);r.json({success:true,message:'Product deleted'})});
app.post('/api/admin/messages',auth,async(q,r)=>{const userId=String(q.body.userId||''),text=String(q.body.text||'').trim();if(!mongoose.isValidObjectId(userId)||!text)return r.status(400).json({success:false,message:'User and message are required'});const m=await Message.create({userId,sender:'admin',text});await audit(q.admin,'MESSAGE_SEND',text,{targetUserId:userId});r.status(201).json({success:true,message:m})});
app.get('/api/admin/audits',auth,async(q,r)=>r.json({success:true,audits:await Audit.find().sort({createdAt:-1}).limit(500)}));
mongoose.connect(MONGO_URL).then(()=>{console.log('MongoDB connected successfully');app.listen(PORT,()=>console.log(`Zonguru admin server running on port ${PORT}`))}).catch(e=>{console.error('MongoDB connection failed:',e.message);process.exit(1)});
